export const OPEN_GRAPH_VIEW = "OPEN_GRAPH_VIEW"
export const OPEN_DEFAULT_VIEW = "OPEN_DEFAULT_VIEW"
export const OPEN_PANEL_VIEW = "OPEN_PANEL_VIEW"
export const SET_SEARCH_KEY = "SET_SEARCH_KEY"


