export const MOVE_COURSE = "MOVE_COURSE"
export const FETCH_COURSES_INIT = "FETCH_COURSES_INIT"
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS"
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE"

